export const CREATE_PROPERTY_STEPS = [
  { label: "Create Property", value: "/create-property" },
  { label: "Guidelines", value: "/create-property/guidelines" },
  { label: "Select Category", value: "/create-property/select-category" },
  { label: "Title & Description", value: "/create-property/title-description" },
  { label: "Location", value: "/create-property/location" },
  { label: "Map Spot", value: "/create-property/map-spot" },
  { label: "Amenities", value: "/create-property/amenities" },
  { label: "Rules", value: "/create-property/rules" },
  { label: "Images", value: "/create-property/images" },
  { label: "Manage Room", value: "/create-property/manage-room" },
  {
    label: "Room Title & Description",
    value: "/create-property/manage-room/title-description",
  },
  { label: "Total Units", value: "/create-property/manage-room/total-units" },
  { label: "Capacity", value: "/create-property/manage-room/capacity" },
  { label: "Highlight", value: "/create-property/manage-room/highlight" },
  { label: "Room Images", value: "/create-property/manage-room/images" },
  { label: "Set Price", value: "/create-property/manage-room/set-price" },
  { label: "Create Peak Rate", value: "/create-property/create-peak-rate" },
  { label: "Unavailabilities", value: "/create-property/unavailabilities" },
  { label: "Summary", value: "/create-property/summary" },
];
